import type { Icon, IconProps } from "@tabler/icons-react";
import {
  IconCrown,
  IconShield,
  IconFlag,
  IconTarget,
  IconBook,
  IconBook2,
  IconBooks,
  IconFeather,
  IconCertificate,
  IconSchool,
  IconLeaf,
  IconTree,
  IconMountain,
  IconSun,
  IconMoon,
  IconStar,
  IconFlame,
  IconSnowflake,
  IconDroplet,
  IconHorse,
  IconFish,
  IconKey,
  IconLock,
  IconBell,
  IconAnchor,
  IconCompass,
  IconMap,
  IconTelescope,
  IconHourglass,
  IconClock,
  IconDiamond,
  IconCoin,
  IconTrophy,
  IconMedal,
  IconPuzzle,
  IconDice5,
  IconCards,
  IconBuildingCastle,
  IconBuildingMonument,
  IconBuildingBridge,
  IconTent,
  IconHammer,
  IconGavel,
  IconScale,
  IconHeart,
  IconEye,
  IconHandStop,
  IconFingerprint,
  IconRainbow,
  IconBolt,
  IconSailboat,
  IconShip,
  IconRocket,
  IconPalette,
  IconBrush,
  IconMusic,
  IconMasksTheater,
  IconBalloon,
  IconUmbrella,
  IconCactus,
  IconApple,
  IconFlower,
  IconClover,
  IconPaw,
  IconBone,
  IconEgg,
  IconCandle,
  IconLamp,
  IconGlobe,
  IconPlanet,
  IconMeteor,
  IconWind,
  IconCloudStorm,
  IconChessKing,
  IconChessQueen,
  IconChessKnight,
  IconChessRook,
  IconChessBishop,
  IconTornado,
  IconVolcano,
  IconWaveSquare,
  IconSwords,
  IconArrowsCross,
  IconSpade,
  IconClubs,
} from "@tabler/icons-react";

/**
 * 콘텐츠(역사 항목)와 무관하게, 시각적으로 뚜렷이 구분되는 아이콘만 골랐다.
 * 방 생성 시 이 풀을 셔플해서 심볼마다 하나씩 중복 없이 배정한다(src/lib/rooms.ts).
 * 57개 심볼을 지원하려면 최소 57개가 필요해서 여유 있게 구성.
 */
export const ICON_POOL: Record<string, Icon> = {
  crown: IconCrown,
  shield: IconShield,
  flag: IconFlag,
  target: IconTarget,
  book: IconBook,
  "book-2": IconBook2,
  books: IconBooks,
  feather: IconFeather,
  certificate: IconCertificate,
  school: IconSchool,
  leaf: IconLeaf,
  tree: IconTree,
  mountain: IconMountain,
  sun: IconSun,
  moon: IconMoon,
  star: IconStar,
  flame: IconFlame,
  snowflake: IconSnowflake,
  droplet: IconDroplet,
  horse: IconHorse,
  fish: IconFish,
  key: IconKey,
  lock: IconLock,
  bell: IconBell,
  anchor: IconAnchor,
  compass: IconCompass,
  map: IconMap,
  telescope: IconTelescope,
  hourglass: IconHourglass,
  clock: IconClock,
  diamond: IconDiamond,
  coin: IconCoin,
  trophy: IconTrophy,
  medal: IconMedal,
  puzzle: IconPuzzle,
  dice: IconDice5,
  cards: IconCards,
  "building-castle": IconBuildingCastle,
  "building-monument": IconBuildingMonument,
  bridge: IconBuildingBridge,
  tent: IconTent,
  hammer: IconHammer,
  gavel: IconGavel,
  scale: IconScale,
  heart: IconHeart,
  eye: IconEye,
  hand: IconHandStop,
  fingerprint: IconFingerprint,
  rainbow: IconRainbow,
  bolt: IconBolt,
  sailboat: IconSailboat,
  ship: IconShip,
  rocket: IconRocket,
  palette: IconPalette,
  brush: IconBrush,
  music: IconMusic,
  masks: IconMasksTheater,
  balloon: IconBalloon,
  umbrella: IconUmbrella,
  cactus: IconCactus,
  apple: IconApple,
  flower: IconFlower,
  clover: IconClover,
  paw: IconPaw,
  bone: IconBone,
  egg: IconEgg,
  candle: IconCandle,
  lamp: IconLamp,
  globe: IconGlobe,
  planet: IconPlanet,
  meteor: IconMeteor,
  wind: IconWind,
  "cloud-storm": IconCloudStorm,
  "chess-king": IconChessKing,
  "chess-queen": IconChessQueen,
  "chess-knight": IconChessKnight,
  "chess-rook": IconChessRook,
  "chess-bishop": IconChessBishop,
  tornado: IconTornado,
  volcano: IconVolcano,
  wave: IconWaveSquare,
  swords: IconSwords,
  crossed: IconArrowsCross,
  spade: IconSpade,
  clubs: IconClubs,
};

export const ICON_NAMES = Object.keys(ICON_POOL);

export function getIconComponent(name: string | null | undefined): Icon | null {
  if (!name) return null;
  return ICON_POOL[name] ?? null;
}

export type { IconProps };
